mergeSort: mergeSort.o BottomUp.o

		g++ -o mergeSort mergeSort.o BottomUp.o


mergeSort.o: mergeSort.cpp
		
		g++ -c mergeSort.cpp


BottomUp.o: BottomUp.cpp
		
		g++ -c BottomUp.cpp


clean: 
	
		rm mergeSort *.o

