CC=g++
CFLAGS= -std=c++11 -w

all:InsertionSort LongLinkedList
	$(CC) $(CFLAGS) -o InsertionSort.exe InsertionSort.o LongLinkedList.o 
	
InsertionSort:InsertionSort.cpp
	$(CC) $(CFLAGS) -c InsertionSort.cpp
	
LongLinkedList:LongLinkedList.cpp
	$(CC) $(CFLAGS) -c LongLinkedList.cpp 